dist: trusty
sudo: required

language: elixir
elixir: 1.4.2
otp_release: 19.3

services:
  - mysql
  - postgresql
  - neo4j

before_script:
  - mysql -e "CREATE DATABASE arsmagbdd;"
  - mysql -e "CREATE USER 'arsmagbdd'@'%' IDENTIFIED BY 'ars_magica';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'arsmagbdd'@'%';"
  - mysql -e "FLUSH PRIVILEGES;"
  - psql -c "CREATE USER vinculi WITH PASSWORD 'Koysteuk'" -U postgres
  - cp config/travis/data.tar.gz ~
  - sudo service neo4j stop
  - sleep 20
  - sudo rm -rf /usr/local/neo4j-3.2.1/data
  - (cd /usr/local/neo4j-3.2.1 && sudo tar xvf ~/data.tar.gz --strip 1)
  - echo 'dbms.allow_format_migration=true' | sudo tee --append /usr/local/neo4j-3.2.1/neo4j.conf
  - sudo sed -i 's|dbms.security.auth_enabled=false|dbms.security.auth_enabled=true|g' /usr/local/neo4j-3.2.1/neo4j.conf
  - cat /usr/local/neo4j-3.2.1/neo4j.conf
  - sudo service neo4j start
  - sleep 30
