dist: trusty
sudo: required

language: elixir
elixir: 1.4.2
otp_release: 19.3

env:
  global:
    - NEO4J_PATH=/usr/local/neo4j-3.2.1
    - NEO4J_CONF_PATH=/usr/local/neo4j-3.2.1/conf

services:
  - mysql
  - postgresql
  - neo4j

before_script:
  - mysql -e "CREATE DATABASE arsmagbdd_test;" -u root
  - mysql -e "CREATE USER 'arsmagbdd'@'localhost' IDENTIFIED BY 'ars_magica';"
  - mysql -e "GRANT ALL ON *.* TO 'arsmagbdd'@'localhost' WITH GRANT OPTION;"
  - mysql -e "FLUSH PRIVILEGES;" -u root
  - mysql -e "SELECT User, Host, Password, plugin FROM mysql.user;" -u root
  - psql -c "CREATE USER vinculi WITH PASSWORD 'Koysteuk';" -U postgres
  - psql -c "ALTER USER vinculi WITH SUPERUSER;" -U postgres
  - psql -c "CREATE DATABASE vinculi_test;" -U postgres
  - sudo service neo4j stop
  - sleep 20
  - mkdir $NEO4J_PATH/data/dbms
  - cp config/travis/auth $NEO4J_PATH/data/dbms/auth
  - echo 'dbms.allow_format_migration=true' | sudo tee --append $NEO4J_CONF_PATH/neo4j.conf
  - echo 'dbms.connector.bolt.listen_address=0.0.0.0:7688' | sudo tee --append $NEO4J_CONF_PATH/neo4j.conf
  - sudo sed -i 's|dbms.security.auth_enabled=false|dbms.security.auth_enabled=true|g' $NEO4J_CONF_PATH/neo4j.conf
  - sudo chown -R travis:travis $NEO4J_PATH/data/dbms
  - sudo service neo4j start
  - sleep 30
  - nvm install 6.2 && nvm use 6.2
  - cd apps/vinculi_web/assets && npm install
  - ./node_modules/brunch/bin/brunch build --production && cd ../../..

script:
  - mix test
  - echo "Re-running tests for each app" ; for app in apps/**; do cd $app && mix test; cd ../.. ; done

deploy:
  provider: heroku
  app: vinculi
  api_key:
    secure: FZQ8NCufJGlV++rUtuKSnRQcl75+8ZQ10xSzdiAPq/G6l1SnN1eV6sYqxUV1vwSAeAlRq2j3fFf50zQtIDOyiEc0FwvsUvFB5cpuaIYYhn2G/yK4DMnb/Z+IT9Sp/nY90nERk5sU0fst6uxxpFvxey44f5jWFJ4O8x4XHWUtc3Cv/FFm7kmS+pMYr6e4rFFI6xBoJcvTK3MdIE50LtAa14tt/nW/CFQDNxhkI7n3hpH1LmJJqBgNT/aFoec0yr4nx4CQZk2JAsog1lKHtUvHLRjY+mol2QhUtMc1EON84yelkrcJyzuQyC1twBoRoMpNfPo9JoxZLt6aI/Ypx79gurgDVNA7Mi/HHe/Q2oceWfmLMnK4h/OvtivK4sog5caN0cjH4XeQQl967WVYj0G3hmxk9WzPxz5iUe9aWwzIfiHEPAsysSrata6Tm5RMS3yx4JgJfrAhsNSFXlDdBJvIzvcKP5/iy9AtrpA22N9TJRY4LDRmctk6398FgjwqFCuV5554FNCSUu2w07qpUAeP/T5P9XibtrUnFhMYTYs1kTnI8mNuBG4ePBvCtPHr6wFsHvrh81Ril6V5YYXFaMY5khcMyiy2j9w91G/N7vaL4gi0ypd/tzttf6LatqMf3hYbujYJndDfTl3jlzPnHh93hrtDQISgoTRcxzVVRrDlJsE=
  buildpack:
    - https://github.com/HashNuke/heroku-buildpack-elixir.git
    - https://github.com/gjaldon/heroku-buildpack-phoenix-static.git