dist: trusty
group: deprecated-2017Q3
sudo: required

language: elixir
elixir: 1.4.2
otp_release: 19.3

services:
  - mysql
  - postgresql
  - neo4j

before_script:
  - mysql -e "CREATE DATABASE arsmagbdd_test;" -u root
  - mysql -e "CREATE USER 'arsmagbdd'@'localhost' IDENTIFIED BY 'ars_magica';"
  - mysql -e "CREATE USER 'arsmagbdd'@'127.0.0.1' IDENTIFIED BY 'ars_magica';"
  - mysql -e "GRANT ALL ON *.* TO 'arsmagbdd'@'localhost' WITH GRANT OPTION;"
  - mysql -e "GRANT ALL ON *.* TO 'arsmagbdd'@'127.0.0.1' WITH GRANT OPTION;"
  - mysql -e "FLUSH PRIVILEGES;" -u root
  - mysql -e "SELECT User, Host, Password, plugin FROM mysql.user;" -u root
  - psql -c "CREATE USER vinculi WITH PASSWORD 'Koysteuk';" -U postgres
  - psql -c "ALTER USER vinculi WITH SUPERUSER;" -U postgres
  - psql -c "CREATE DATABASE vinculi_test;" -U postgres
  - cp config/travis/data.tar.gz ~
  - sudo service neo4j stop
  - sleep 20
  - ls -latr /var/lib/neo4j
  - ls -latr /var/lib/neo4j/data
  - sudo rm -rf /var/lib/neo4j/data/*
  - (cd /var/lib/neo4j && sudo tar xvf ~/data.tar.gz)
  - echo 'dbms.allow_format_migration=true' | sudo tee --append /etc/neo4j/neo4j.conf
  - echo 'dbms.connector.bolt.listen_address=0.0.0.0:7688' | sudo tee --append /etc/neo4j/neo4j.conf
  - echo 'dbms.connector.http.listen_address=0.0.0.0:7474' | sudo tee --append /etc/neo4j/neo4j.conf
  - sudo sed -i 's|dbms.security.auth_enabled=false|dbms.security.auth_enabled=true|g' /etc/neo4j/neo4j.conf
  - cat /etc/neo4j/neo4j.conf
  - sudo chown -R neo4j:adm /var/lib/neo4j/data
  - sudo chown neo4j:adm /var/lib/neo4j/data/databases
  - sudo chown neo4j:adm /var/lib/neo4j/data/dbms
  - sudo service neo4j start
  - sleep 30